let greeting ='hello';
console.log(greeting);
let name= 'owu';
console.log(name);
let domen ='com';
console.log(domen);
let ua = 'country';
console.log(ua);
let number1=1;
console.log(number1);
let number10=10;
console.log(number10);
let numbermius999=-999;
console.log(numbermius999);
let number123=123;
console.log(number123);
let pi=3.14;
console.log(pi);
let number2point7=2.7;
console.log(number2point7);
let number16=16;
console.log(number16);
let bool1=true;
console.log(bool1);
let bool2=false;
console.log(bool2);

let firstNme='Yura';
let lastName='Hvozd';
//let result=firstNme + ' ' + lastName;
//console.log(result);
let result = `${firstNme} ${lastName}`;
console.log(result);

let a =100;
console.log(typeof a);
let b = '100';
console.log(typeof b);
let s = true;
console.log(typeof s);
